# Generated by Django 3.0.3 on 2020-04-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=50)),
                ('harga', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('alamat', models.TextField(null=True)),
                ('qty', models.PositiveIntegerField()),
                ('total_bayar', models.PositiveIntegerField(null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.Barang')),
            ],
        ),
    ]
