# Generated by Django 3.0.2 on 2020-05-12 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pict',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pict',
            name='describe',
            field=models.TextField(),
        ),
    ]
