# Generated by Django 3.0.2 on 2020-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0002_auto_20200512_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
