# Generated by Django 3.0.2 on 2020-05-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0004_auto_20200512_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
